apiVersion: v1
kind: Pod
metadata:
  name: kafka-test-pod
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: ['sh', '-c', 'echo The app is running! && sleep 3600']
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: kafka-configmap
        items:
        - key: bootstrap.servers
          path: keys
        
