apiVersion: v1
kind: Service
metadata:
  name: kafka-cloud-proxy
  namespace: kafka-ca1

spec:
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
  type: NodePort
  selector:
    app: kafka-cloud-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-cloud-proxy
  namespace: kafka-ca1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-cloud-proxy
  template:
    metadata:
      labels:
        app: kafka-cloud-proxy
    spec:
      containers:
        - name: kafka-cloud-proxy
          image: confluentinc/cp-kafka-rest:5.1.3
          imagePullPolicy: Always
          command: ['kafka-rest-start']
          args: ['/etc/config/properties']
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: kafka-configmap
            items:
            - key: properties
              path: properties

